### ISSUE TITLE
I'm trying to understand the csv DB and how to maybe read or write it in another software.

### ISSUE THREAD

**Issue by elico** [techtacoriginal/offlinebay#13] opened 2018-10-14 23:45 UTC
The file has this:
```
#ADDED;HASH(B64);NAME;SIZE(BYTES)
2018-Jan-31 21:01:58;rlrRc5m5ZYEb0WupkEuThZVEUHM=;"Windows 10 Version 1709 x64 (Updated Dec 2017)";10388732142
```
But the info hash is: ```DB76A14AF3267009785F93454E84C3883A3BD21B```
So how technically I get from the ```rlrRc5m5ZYEb0WupkEuThZVEUHM=``` back to the info hash?
I have seen the JS at somewhere but something is missing for me to understand it.

**Comment by elico** [comment] 2018-10-15 00:04
OK I found the issue.
I am using ruby and I matched the wrong records in the csv file.
```
#!/usr/bin/env ruby
require "base64"

target = "DB76A14AF3267009785F93454E84C3883A3BD21B"

# Read the recodrd from csv and found the base 64 line
base64string="23ahSvMmcAl4X5NFToTDiDo70hs="
puts Base64.decode64(base64string).unpack("H*").first.upcase
> DB76A14AF3267009785F93454E84C3883A3BD21B 
```

**Comment by techtacoriginal** [comment] 2018-10-15 20:13
Closing this since the issue is solved. 🤘

**Closed** 2018-10-15 20:14 UTC
Labels: question/non-issue
